app = "torrserver"
primary_region = "otp"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  TS_PORT = "8090"

[[services]]
  processes = ["app"]
  internal_port = 8090
  auto_stop_machines = false
  auto_start_machines = false

  [[services.ports]]
    port = 8090

[deploy]
  strategy = "immediate"